sudo: required

language: generic

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

services:
  - docker

script:
  - docker-compose -f docker-compose.test.yml up --build

branches:
  only:
    - master
