export enum CategoryName {
  Buttons = "Buttons",
  Cards = "Cards",
  Dropdown = "Dropdown",
  FlexWrapper = "FlexWrapper",
  Icons = "Icons",
  TextFields = "Text-Fields",
  Links = "Links",
  Modal = "Modal",
  Notification = "Notification",
  Table = "Table",
  Tabs = "Tabs",
  Tags = "Tags",
  Tiles = "Tiles",
  TimePicker = "TimePicker",
  DatePicker = "DatePicker",
  Tooltips = "Tooltips",
  SelectionControls = "Selection-Controls",
  Accordion = "Accordion",
  FileUpload = "FileUpload",
  Others = "Others"
}
